name: Docker CI

on:
  push:
    branches:
      - '*'
      - !next
      - !master

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: build-image
      run: docker build .